[theme]
base="dark"
primaryColor="#C99700"  # ND Gold
backgroundColor="#0E1117"  # Jet Black/Charcoal
secondaryBackgroundColor="#1E2A38"  # ND Navy Tint
textColor="#F8F9FA"  # Near white for readability
font="sans serif"
